# Generated by Django 3.0.3 on 2020-04-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webjesemar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscriptor',
            name='telefono',
            field=models.CharField(max_length=11),
        ),
    ]
